### ISSUE TITLE
[BUG] Crash due to conflict between libcef and gtk using the glib event loop on linux

### ISSUE THREAD

**Issue by Gol-D-Ace** [obsproject/obs-browser#219]
## Platform

Operating system and version: Any Linux distro using a desktop environment that makes use of GTK like for example the standard flavor of Ubuntu
OBS Studio version: 25.0.4 (any that include the browser source and therefore libcef)

## Expected Behavior

Not have the file dialog / OBS hang or crash when using a file dialog to choose a file for example an image on the image source.
## Current Behavior

The file dialog will hang or crash including OBS and makes it impossible to select a file.
## Steps to Reproduce

1. Compile OBS Studio with the browser source or install a binary package that includes the browser source.
2. Be on a distro that uses GTK for the desktop environment (file dialog) like for example the standard Ubuntu flavor.
3. Open a file choose dialog. Add for example an image source and click browse.
4. Try to select a file. It may work on the first try. Try a second or third time in that case or leave the dialog open for a bit.
5. The dialog and OBS will freeze and eventually crash.

## Additional information

Followup issue for https://github.com/obsproject/obs-studio/issues/2644 to get more exposure

This issue seems to get caused by GTK and libcef both using the glib event loop and causing a conflict. Using for example the QT dialogs (none native) will work around the issue.

Unfortunately this work around reduces functionality on GTK and might even break OBS installs entirely on distros where the qt5 configuration tool isn't available because the deb package will depend on it.

**Comment by Fenrirthviti** [comment]
Just as a note here, we are rolling back the deployment of the browser source plugin on Linux until this can be resolved. If anyone has experienced this issue and has ideas on how to properly fix it, please let us know.

**Comment by HarleyLorenzo** [comment]
Would it be possible to always force a non-native file picker (like with the fix for the font and color picker crashes) or does that not work on some distros?

**Comment by Gol-D-Ace** [comment]
Unfortunately the none native file dialog (Qt) lacks functionality.
Mainly network but probably more.

**Comment by kkartaltepe** [comment]
Original issue for reference https://github.com/obsproject/obs-browser/issues/141

The proposed solution there doesnt affect native dialogs which in gtk land will likely all use g(tk)lib for messaging and threading support.

**Comment by ebassi** [comment]
Hi, GTK developer here.

Is there any chance to have a backtrace of the crash to analyze?

**Comment by kkartaltepe** [comment]
From the original issue for reference:
https://pastebin.com/4wnggfUQ

**Comment by Gol-D-Ace** [comment]
@ebassi 
Thank you for contacting us.

This is the backtrace on Ubuntu 19.10
```
Thread 1 "obs" received signal SIGTRAP, Trace/breakpoint trap.
0x00007fff9ba16ea3 in ?? () from /usr//lib/obs-plugins/libcef.so
(gdb) bt full
#0  0x00007fff9ba16ea3 in  () at /usr//lib/obs-plugins/libcef.so
#1  0x00007fff9ba1a157 in  () at /usr//lib/obs-plugins/libcef.so
#2  0x00007fff9ba1a7ea in  () at /usr//lib/obs-plugins/libcef.so
#3  0x00007fff9b9f00bd in  () at /usr//lib/obs-plugins/libcef.so
#4  0x00007fff9b9ff44c in  () at /usr//lib/obs-plugins/libcef.so
#5  0x00007fff9b9ff899 in  () at /usr//lib/obs-plugins/libcef.so
#6  0x00007fff9b9c05ff in  () at /usr//lib/obs-plugins/libcef.so
#7  0x00007ffff409c8bd in g_main_context_dispatch ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#8  0x00007ffff409cb40 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#9  0x00007ffff409ce33 in g_main_loop_run ()
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#10 0x00007fffeacab357 in gtk_dialog_run ()
    at /lib/x86_64-linux-gnu/libgtk-3.so.0
#11 0x00007fffeb223ec9 in  ()
    at /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so
#12 0x00007ffff62f0f31 in QDialog::exec() ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#13 0x00007ffff63042b5 in QFileDialog::getOpenFileUrl(QWidget*, QString const&, QUrl const&, QString const&, QString*, QFlags<QFileDialog::Option>, QStringList const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff63043a4 in QFileDialog::getOpenFileName(QWidget*, QString const&, QString const&, QString const&, QString*, QFlags<QFileDialog::Option>) ()
```

**Comment by kkartaltepe** [comment]
Iirc the original stack was from a release with debug symbols. If you attempt to run debug chromium you will die on asserts checking that messages are appropriately ordered (obviously when the message is not coming from chromium that check is going to have a bad time)

**Comment by ebassi** [comment]
@Gol-D-Ace Thanks, much appreciated.

There are still missing debugging symbols for the libcef shared library, but since you're using `gtk_dialog_run()` I'd go out on a limb and say there's some re-entrancy issue due to the nested main loop.

**Comment by Gol-D-Ace** [comment]
Tried it again and now I'm getting this.
```
Thread 1 "obs" received signal SIGTRAP, Trace/breakpoint trap.
0x00007fff9ba16ea3 in operator() ()
    at ../../base/threading/sequenced_task_runner_handle.cc:26
26	../../base/threading/sequenced_task_runner_handle.cc: Datei oder Verzeichnis nicht gefunden.
(gdb) bt full
#0  0x00007fff9ba16ea3 in operator() ()
    at ../../base/threading/sequenced_task_runner_handle.cc:26
#1  0x00007fff9ba16ea3 in Get() ()
    at ../../base/threading/sequenced_task_runner_handle.cc:26
#2  0x00007fff9ba1a157 in GetTaskRunner () at ../../base/timer/timer.cc:189
#3  0x00007fff9ba1a157 in PostNewScheduledTask() ()
    at ../../base/timer/timer.cc:176
#4  0x00007fff9ba1a7ea in RunUserTask() () at ../../base/timer/timer.cc:296
#5  0x00007fff9b9f00bd in Run () at ../../base/callback.h:97
#6  0x00007fff9b9f00bd in RunTask() ()
    at ../../base/task/common/task_annotator.cc:114
#7  0x00007fff9b9ff44c in DoWorkImpl() ()
    at ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:363
#8  0x00007fff9b9ff899 in non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ()
    at ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:260
#9  0x00007fff9b9c05ff in HandleDispatch ()
    at ../../base/message_loop/message_pump_glib.cc:263
#10 0x00007fff9b9c05ff in WorkSourceDispatch() ()
    at ../../base/message_loop/message_pump_glib.cc:109
#11 0x00007ffff409b8bd in g_main_context_dispatch ()
--Type <RET> for more, q to quit, c to continue without paging--c
    at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff409bb40 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff409be33 in g_main_loop_run () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007fffeacae357 in gtk_dialog_run () at /lib/x86_64-linux-gnu/libgtk-3.so.0
#15 0x00007fffeb226ec9 in  () at /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk3.so
#16 0x00007ffff62eff31 in QDialog::exec() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff63032b5 in QFileDialog::getOpenFileUrl(QWidget*, QString const&, QUrl const&, QString const&, QString*, QFlags<QFileDialog::Option>, QStringList const&) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff63033a4 in QFileDialog::getOpenFileName(QWidget*, QString const&, QString const&, QString const&, QString*, QFlags<QFileDialog::Option>) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x0000555555704a9f in  ()
#20 0x000055555570628b in  ()
#21 0x00007ffff56293f8 in QMetaObject::activate(QObject*, int, int, void**) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff61e1236 in QAbstractButton::clicked(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff61e145e in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff61e28a3 in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff61e2a65 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x00007ffff612f04e in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#27 0x00007ffff60eca86 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#28 0x00007ffff60f6053 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#29 0x00007ffff55fda2a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x00007ffff60f5157 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#31 0x00007ffff614b14d in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#32 0x00007ffff614dfdc in  () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#33 0x00007ffff60eca86 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#34 0x00007ffff60f5e00 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#35 0x00007ffff55fda2a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#36 0x00007ffff59e5d73 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#37 0x00007ffff59e75fb in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#38 0x00007ffff59c126b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Gui.so.5
#39 0x00007fffec08d657 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#40 0x00007ffff55fc5cb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#41 0x00007ffff5604336 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#42 0x00005555555c9478 in main ()
(gdb) 
```

**Comment by kkartaltepe** [comment]
Ah that is similar to the debug build crashes that check sequence but instead this looks like its also in release.  https://chromium.googlesource.com/chromium/src/+/refs/tags/75.0.3770.156/base/threading/sequenced_task_runner_handle.cc#26

**Comment by ebassi** [comment]
I do hope the task runner is not causing the source dispatch to happen in a different thread than the one that is spinning the GLib main loop of `gtk_dialog_run()`, because that would be very bad indeed.

**Comment by crujp100** [comment]
j'ai installé la version obs studio 27.07 sur ubuntu 18.04,  lorsque je clique sur la case "start streaming" celle-ci reste grisée, il se produit un bouclage rendant le système instable, il faut stopper le processus OBS ou redémarrer le sytème et cela depuis le début de la version OBS 25.0 . j'ai donc réinstallé la version d'OBS 21.0 recommandée par ubuntu. Celle-ci fonctionne correctement.

I installed the obs studio version 27.07 on ubuntu 18.04, when I click on the 'start streaming' box it remains grayed out, a looping occurs making the system unstable, you have to stop the OBS process or restart the system and this since the start of OBS 25.0. so I reinstalled the version of OBS 21.0 recommended by ubuntu. It works properly.

**Comment by ConorOG** [comment]
> I do hope the task runner is not causing the source dispatch to happen in a different thread than the one that is spinning the GLib main loop of `gtk_dialog_run()`, because that would be very bad indeed.

That would seem like a fundamental design issue? But this plugin has been working before?

**Comment by Fenrirthviti** [comment]
This plugin has not been working before, this was our first attempt at releasing on Linux. There is another similar browser source plugin that was developed by a third party, but is no longer maintained.

**Comment by leotrs** [comment]
Hello, has there been any progress here? It is a very unfortunate situation to not have the browser plugin available.

**Comment by ccoenen** [comment]
I usually don't `+1` issues, but it is very silent here. I'm not asking for an ETA or something, but I would also like to know it someone is looking into this, or if someone has a workaround in the meantime.

**Comment by davidfurey** [comment]
I'm using https://github.com/bazukas/obs-linuxbrowser/releases/tag/0.6.1 as a workaround.

**Comment by arjenpdevries** [comment]
Another workaround: https://github.com/obsproject/obs-studio/issues/2644#issuecomment-623168704

**Comment by dodgepong** [comment]
Unfortunately this is something we haven't had the bandwidth to take a closer look at yet. If anyone else out there wants to take a crack at it, then please do, by all means.

**Comment by fabianbur** [comment]
I am a user of free software and Linux in particular. I always use that particular option and it is the reason to have a Windows partition on my laptop. When the official support for the plugin in Linux was announced, I was very happy, I thought that the developers were finally giving it the importance that corresponds to Linux users, then my disappointment was great and with the last message more. I am not an expert programmer in this particular problem, if that were the case I would have fixed it myself. How many developers outside the OBS project are willing to give their time to fix this bug? Until now nobody and I fear that this will continue. Without a real interest from the OBS team in fixing this bug, without a developer assigned, this serious bug will remain open for months or years. How unfortunate!

**Comment by dodgepong** [comment]
There are many talented developers in the Linux community. Unfortunately this is a case where we simply don't have enough people to look at everything. Practically speaking, OBS only has one full-time developer. We welcome contribution from the community. Be the change you want to see in the world.

**Comment by fabianbur** [comment]
It is definitely a matter of priorities...

**Comment by dodgepong** [comment]
Correct, it is definitely a matter of priorities. Sadly, this issue is not the top priority, believe it or not. It might be your top priority, but it is not the top priority for the project as a whole in the broader scheme of things. We don't really have enough people to focus on very many things at one time. Would you like to volunteer to fill the gap?

**Comment by fabianbur** [comment]
Yes, I am willing to volunteer my time to fix this bug. I have done voluntary translations on another project and other voluntary things on other projects, I have also reported bugs. It doesn't occur to me this time how I could volunteer to fix this bug without being a developer, as I mentioned before and surely you read it. But if you mention it, I hope it is because you have an idea about it, I listen to you.

**Comment by dodgepong** [comment]
I don't have a specific idea myself (I'm not a C++ dev, nor am I much of a Linux desktop user) but I would encourage you to read the earlier discussions between @ebassi and @Gol-D-Ace for some more context.

**Comment by fabianbur** [comment]
> I don't have a specific idea myself (I'm not a C++ dev, nor am I much of a Linux desktop user) but I would encourage you to read the earlier discussions between @ebassi and @Gol-D-Ace for some more context.

Thank you for your contribution. I am subscribed to this thread, what you mentioned was the first thing I read.

**Comment by kkartaltepe** [comment]
>  It doesn't occur to me this time how I could volunteer to fix this bug without being a developer

Without being an expert in C++ there is not a lot of meaningful contribution you can do. This is why this bug has stagnated, diagnosing and fixing it is a non-trivial problem.

If you can find an expert in Chromium and Glib and convince them to work on this bug that's the best you can do without being an expert yourself. Though someone appears to have convinced a GTK developer (the closest to glib ive seen) to take a look, they appear to have been dissuaded from looking further by the chromium codebase (who can really blame someone for that?).

**Comment by fabianbur** [comment]
> Without being an expert in C++ there is not a lot of meaningful contribution you can do.

His answer seems to me more sincere and honest.

**Comment by cpw** [comment]
Fascinating. I just came across this bug. I've been using debian, gnome-shell and obs builds with browser plugin since 25 landed. I have never noticed this issue. I seem to be able to browse images with the file browser just fine?

**Comment by cg2121** [comment]
Workaround for now: https://github.com/obsproject/obs-studio/pull/3177

**Comment by Gol-D-Ace** [comment]
Not sure if we should leave this open or not with the none native file dialog PR merged.

**Comment by Fenrirthviti** [comment]
If migrating away from the native file dialog is the solution and not a workaround, we can close this, but if it is something we are not looking to keep long term, this should remain open.

**Comment by PrinceKael** [comment]
Any word on when this will be included for Linux users?

**Comment by nicolaiparlog** [comment]
With obsproject/obs-studio#3177 merged, it would be great if the browser source made it into the next OBS release. If that's not possible for whatever reason it would be great to have a manual on how to get this plugin to work on our own, so we can give it a try even if it's not shipped. Is there such a document?

**Comment by BloodyIron** [comment]
> With [obsproject/obs-studio#3177](https://github.com/obsproject/obs-studio/pull/3177) merged, it would be great if the browser source made it into the next OBS release. If that's not possible for whatever reason it would be great to have a manual on how to get this plugin to work on our own, so we can give it a try even if it's not shipped. Is there such a document?

Wait, if that was merged, does that mean the next release will not have network share connectivity but have web URL ability instead? I thought that fork was supposed to be a temporary work around until this ( #219 ) was comprehensively fixed.

I'm honestly really surprised to find this issue exists. Was really hyped up to use this feature in my broadcast this evening, and starting to feel like features aren't actually tested on all platform. And now feeling like Linux is treated like a 2nd class citizen for this project :/

**Comment by dodgepong** [comment]
You will still be able to access network shares, though it will require a workaround. You should be able to navigate to something like `/var/run/gvfs/<mountname>` to access your network share instead of through the Gnome shortcut.

It's a difficult situation. Our choices right now are either a) continue to withhold the browser source from all Linux builds due to this GTK crash, or b) release this workaround for all Linux builds, but with this one caveat that has a workaround available. The solution of c) fix the underlying issue appears to be a very deep-rooted conflict between CEF and GTK that does not have an easy solution, and nobody in the community has really stepped up to work on it, so this is the best we can do right now.

**Comment by BloodyIron** [comment]
I'm okay with giving up network shares right now, so long as an issue is made to track a comprehensive solution that provides both, eventually. Is that the plan, or?

Right now it's the browser ability I was looking to leverage.

**Comment by dodgepong** [comment]
#219 will remain open to track the issue.

**Comment by BloodyIron** [comment]
Alright. Is the temporary fix coming in 25.0.9 then or what?

**Comment by dodgepong** [comment]
It will be coming in 26.

**Comment by BloodyIron** [comment]
As in the next MAJOR version? How long will that be to release???

**Comment by dodgepong** [comment]
Be on the lookout for a beta release in the next few weeks.

**Comment by BloodyIron** [comment]
Why wouldn't this go into a minor release instead?

**Comment by dodgepong** [comment]
Video production is a complicated industry, and we tend to prefer to release infrequently so as to reduce the number of interruptions users might have to their workflow. A wayward update at the wrong time carries a lot of risk to producers, so we don't tend do make frequent small releases unless they are hotfixes for a major problem.

You're always free to make a build yourself. Our only official Linux binary is the PPA, so if you're using the Snap for example, you could discuss the possibility of an intermediate update with maintainers of that if you wish.

**Comment by BloodyIron** [comment]
Building from source doesn't work for me as I prefer my package manager to be aware of all software on the system.

Considering that the build release cycle is taking such things into consideration, would not it seem prudent to have a Beta and Release PPA cycle? That way something like the relevant temporary merge could go into a beta version of 25.0.9, and then eventually go release?

I mean, I even check the release history on github for OBS-Studio and there's RC's for major versions, why no beta streams of minor revisions?

**Comment by Fenrirthviti** [comment]
This discussion is very off-topic to the issue, and should be moved elsewhere. If you'd like to see beta channels, feel free to submit an RFC for the functionality, or stop by our Discord to discuss further.

Let's keep this on-topic so the actual issue can be addressed and fixed, and we don't need a workaround anymore.

**Comment by C-Duv** [comment]
Option b) with workaround for network shares is great.
It's a solution that allow both features to work for everyone 👍

**Comment by PrinceKael** [comment]
As long as the browser source feature is included asap I don't mind it as a temporary measure. This feature is pretty important as without it you can't have stream alerts and other cool things that every other streamer has on Windows.

**Comment by LiamDawe** [comment]
Giving up giving up network shares is a really tiny blip on an otherwise extremely important feature needed in OBS Studio for Linux, glad to see the workaround was merged to get around it for now. Thanks for the hard work everyone :+1:

**Comment by Gol-D-Ace** [comment]
@LiamDawe 
They are still available just harder to find.
For example with gvfs
run/user/userid/gvfs

**Comment by LiamDawe** [comment]
Goodnewseveryone.gif there's a new RC out that should have it in: https://github.com/obsproject/obs-studio/releases/tag/26.0.0-rc1

**Comment by Gol-D-Ace** [comment]
Hi
We are currently testing the Linux browser source in the unstable PPA for Focal.and Bionic x64.

See https://obsproject.com/forum/threads/obs-studio-26-0-release-candidate.129075/ for more informations.

**Comment by BloodyIron** [comment]
So far the Browser functionality in the beta version is working just fine for me! No issues observed thus-far. Required me to upgrade from Ubuntu 19.10 to 20.04, but I was already aiming to do that since ROCm now supports 20.04 (MONTHS LATE).

Thanks for the help in making this happen! To all! :D

**Comment by GeorgesStavracas** [comment]
I've been taking a look on and off on this issue, and I think using a non-native file picker (i.e. always forcing Qt's file picker) is a good way to work around it. The fundamental issue here is that the file picker is in the same process of OBS Studio, and there are 3 different toolkits interacting (GTK, CEF, and QT), which is... not a great thing to do. I think an even better way forward, at least on Linux, is using an out-of-process file picker by using the file chooser portal. While technically possible, it is relatively recent (~4 years old). Being out-of-process means it can use whatever toolkit it wants and it won't interefere with the OBS Studio process. The (unofficial) Flatpak version of OBS Studio already uses it by default, and thus this problem doesn't occur there.

If other developers think it's okay to investigate making OBS Studio try and use portal when available, and falling back to non-native if not, I can prepare a pull request for that. Notice that it is perfectly okay to use portals outside of a sandbox technology.

**Comment by aleixpol** [comment]
Then this is something you can address in the QPlatformTheme you are using. In Plasma we are already doing it for the mobile use-case where it will always go through the portal even when running outside: https://invent.kde.org/plasma/plasma-integration/-/merge_requests/4

I'm assuming this is something you could do from somewhere here:
https://github.com/FedoraQt/QGnomePlatform

Maybe @grulicha has a better idea.

**Comment by grulja** [comment]
> Then this is something you can address in the QPlatformTheme you are using. In Plasma we are already doing it for the mobile use-case where it will always go through the portal even when running outside: https://invent.kde.org/plasma/plasma-integration/-/merge_requests/4
> 
> I'm assuming this is something you could do from somewhere here:
> https://github.com/FedoraQt/QGnomePlatform
> 
> Maybe @grulicha has a better idea.

We can do the same in QGnomePlatform, that shouldn't be a problem and will avoid issues like this in future. However, there is still a Gtk3 platform theme in Qt itself.

**Comment by grulja** [comment]
> > Then this is something you can address in the QPlatformTheme you are using. In Plasma we are already doing it for the mobile use-case where it will always go through the portal even when running outside: https://invent.kde.org/plasma/plasma-integration/-/merge_requests/4
> > I'm assuming this is something you could do from somewhere here:
> > https://github.com/FedoraQt/QGnomePlatform
> > Maybe @grulicha has a better idea.
> 
> We can do the same in QGnomePlatform, that shouldn't be a problem and will avoid issues like this in future. However, there is still a Gtk3 platform theme in Qt itself.

Done: https://github.com/FedoraQt/QGnomePlatform/commit/02d0b3e72d00be5ab529f05378ed76f849046e1a

It will use xdg-desktop-portal only in case the FileChooser portal is in version 3 and newer, otherwise it will be missing support for opening folders.

**Comment by AlexWayfer** [comment]
> Goodnewseveryone.gif there's a new RC out that should have it in: https://github.com/obsproject/obs-studio/releases/tag/26.0.0-rc1



> Hi
> We are currently testing the Linux browser source in the unstable PPA for Focal.and Bionic x64.
> 
> See https://obsproject.com/forum/threads/obs-studio-26-0-release-candidate.129075/ for more informations.

Stable 26 has been released 2 months ago: https://github.com/obsproject/obs-studio/releases/tag/26.0.0

Why this issue is not closed? What the news? I still see no browser in the main Arch Linux package.

**Comment by LiamDawe** [comment]
Then bug the people responsible for the Arch packaging, that's not up to the OBS team.

**Comment by maxdrash** [comment]
Yes the bug is solved and this ticket can be closed, like the first issue: https://github.com/obsproject/obs-studio/issues/2644
Thank you everyone.

**Comment by dodgepong** [comment]
Technically the bug still exists, but there's a workaround in place that avoids the issue.

**Comment by Gol-D-Ace** [comment]
I see it like dodgepong.
The original cause isn't fixed.

The workaround is to use qt dialogs and enable the use qt loop cmake flag which got originally introduced for macOS.

**Comment by maxdrash** [comment]
Oh sorry, my fault.

**Comment by codl** [comment]
@AlexWayfer:
>  I still see no browser in the main Arch Linux package.

See https://bugs.archlinux.org/task/66008:

> From what I can see, it would mean moving AUR package cef-minimal-3770 to [community]. I'm not sure I see that happening.

**Comment by AlexWayfer** [comment]
> @AlexWayfer:
> 
> > I still see no browser in the main Arch Linux package.
> 
> See https://bugs.archlinux.org/task/66008:
> 
> > From what I can see, it would mean moving AUR package cef-minimal-3770 to [community]. I'm not sure I see that happening.

Thank you!

**Comment by AlexWayfer** [comment]
Also, at least after closing this issue, please add "Building on Linux" instructions to README, I see there only for Windows and macOS ("OSX").

**Comment by brutalcrozt** [comment]
`v 26` already includes the obs-browser. I upgrade mint 18 to 21 and verifying it, IMO we can start a new issue tracker for older Linux if that wanted

**Comment by Gol-D-Ace** [comment]
@AlexWayfer 
Usually the browser source gets build together with OBS.
You can find instructions for this in the OBS Studio wiki.

**Comment by Gol-D-Ace** [comment]
Also just letting you guys know that since the newer CEF we no longer have to use the qt loop.

Perhaps native file Dialogs no longer cause crashing but I can't easily test this by reverting commits unfortunately.

**Comment by kkartaltepe** [comment]
I was also playing with the new cef version, I suspect they finally moved to their own glib message pump instead of using the default one resolving the issue.

**Comment by GeorgesStavracas** [comment]
Hm, does that mean OBS Studio doesn't need to disable GLib's mainloop anymore?

**Comment by kkartaltepe** [comment]
This should be all you need to revert the dialogs and use the glib message pump. It didnt crash for me forcing the gtk file selector and leaving it open for a while (fingers crossed)

```diff
diff --git a/UI/obs-app.cpp b/UI/obs-app.cpp
index a415b3f4d..bfa91546e 100644
--- a/UI/obs-app.cpp
+++ b/UI/obs-app.cpp
@@ -1940,10 +1940,6 @@ static int run_program(fstream &logFile, int argc, char *argv[])
 		Qt::HighDpiScaleFactorRoundingPolicy::PassThrough);
 #endif
 
-#if !defined(_WIN32) && !defined(__APPLE__) && BROWSER_AVAILABLE
-	setenv("QT_NO_GLIB", "1", true);
-#endif
-
 	QCoreApplication::addLibraryPath(".");
 
 #if __APPLE__
diff --git a/UI/qt-wrappers.cpp b/UI/qt-wrappers.cpp
index 76c532043..13b8d4613 100644
--- a/UI/qt-wrappers.cpp
+++ b/UI/qt-wrappers.cpp
@@ -351,61 +351,32 @@ void setThemeID(QWidget *widget, const QString &themeID)
 
 QString SelectDirectory(QWidget *parent, QString title, QString path)
 {
-#if defined(BROWSER_AVAILABLE) && defined(__linux__)
-	QString dir = QFileDialog::getExistingDirectory(
-		parent, title, path,
-		QFileDialog::ShowDirsOnly | QFileDialog::DontResolveSymlinks |
-			QFileDialog::DontUseNativeDialog);
-#else
 	QString dir = QFileDialog::getExistingDirectory(
 		parent, title, path,
 		QFileDialog::ShowDirsOnly | QFileDialog::DontResolveSymlinks);
-#endif
-
 	return dir;
 }
 
 QString SaveFile(QWidget *parent, QString title, QString path,
 		 QString extensions)
 {
-#if defined(BROWSER_AVAILABLE) && defined(__linux__)
-	QString file = QFileDialog::getSaveFileName(
-		parent, title, path, extensions, nullptr,
-		QFileDialog::DontUseNativeDialog);
-#else
 	QString file =
 		QFileDialog::getSaveFileName(parent, title, path, extensions);
-#endif
-
 	return file;
 }
 
 QString OpenFile(QWidget *parent, QString title, QString path,
 		 QString extensions)
 {
-#if defined(BROWSER_AVAILABLE) && defined(__linux__)
-	QString file = QFileDialog::getOpenFileName(
-		parent, title, path, extensions, nullptr,
-		QFileDialog::DontUseNativeDialog);
-#else
 	QString file =
 		QFileDialog::getOpenFileName(parent, title, path, extensions);
-#endif
-
 	return file;
 }
 
 QStringList OpenFiles(QWidget *parent, QString title, QString path,
 		      QString extensions)
 {
-#if defined(BROWSER_AVAILABLE) && defined(__linux__)
-	QStringList files = QFileDialog::getOpenFileNames(
-		parent, title, path, extensions, nullptr,
-		QFileDialog::DontUseNativeDialog);
-#else
 	QStringList files =
 		QFileDialog::getOpenFileNames(parent, title, path, extensions);
-#endif
-
 	return files;
 }
```

**Comment by Gol-D-Ace** [comment]
Maybe I'm remembering wrong but afaik it's still required on macOS @kkartaltepe

**Comment by Gol-D-Ace** [comment]
Considering that this issue doesn't seem to 
be happening anymore with CEF 4280 should the issue be closed?

**Comment by maxdrfr** [comment]
Give us more time to test with CEF 4280 as it was still indicated 3770 in the official building guide for 26.1.1 published 23 days ago and personaly, I need to push production tests to approve.

**Comment by Gol-D-Ace** [comment]
Sure.
The wiki just got updated btw. with links to a newer CEF build.

**Comment by Gol-D-Ace** [comment]
I see that @WizardCM did rewrite the build instructions.
Thanks for that.

**Comment by Joan31** [comment]
Hi,
For now the only solution to run OBS with this feature, is to make the package following the wiki ?
Or it is better to wait a new version of OBS and install it directly from repo with this fix included ?

**Comment by Gol-D-Ace** [comment]
@Joan31 For Ubuntu you could try out the unstable PPA.
The issue is bypassed though even in the stable PPA.

Other repos / distributions will need to update the used CEF version.

You can either wait until they do that or build.obs including the browser source yourself.

**Comment by Joan31** [comment]
@Gol-D-Ace 

I'm on Arch Linux. I can build muy own OBS.
But I requested to the community packages to update OBS with this fix

https://bugs.archlinux.org/task/69516

**Comment by Joan31** [comment]
FYI on AUR https://aur.archlinux.org/packages/obs-studio-git/ it is ok with the good CEF version 4280.
I tested it and it work.

**Comment by maxdrfr** [comment]
Tested and approved. Everything works well after several hours on Debian 10.
However, the sound still does not come out through an internal and separate audio source from LIBOBS but to pulseaudio from obs-browser-page thread and this is a problem.
No browser audio source in the mixer panel.

There is a regression from this PR who enhanced this ability to control volume ?
https://github.com/obsproject/obs-browser/issues/11

**Comment by WizardCM** [comment]
> No browser audio source in the mixer panel.

@maxdrfr Make sure to enable "Control Audio via OBS" in the Browser Source's properties.

**Comment by maxdrfr** [comment]
> > No browser audio source in the mixer panel.
> 
> @maxdrfr Make sure to enable "Control Audio via OBS" in the Browser Source's properties.

Thank you, my fault.

**Comment by hollunder** [comment]
Is this actually a plugin that can be built on its own like it is the case with the two outdated external ones? If so that would at least make packaging a bit easier. At least on Arch CEF is not in any official repository, probably for a good reason. As a plugin it could live in the AUR and could be used with OBS from the official binary repos.

**Comment by RytoEX** [comment]
> Is this actually a plugin that can be built on its own like it is the case with the two outdated external ones? If so that would at least make packaging a bit easier. At least on Arch CEF is not in any official repository, probably for a good reason. As a plugin it could live in the AUR and could be used with OBS from the official binary repos.

We no longer support building obs-browser separately from obs-studio because there are features in obs-studio that rely on building the application with obs-browser enabled.  We recommend building obs-studio with obs-browser enabled, per [the build instructions on the obs-studio wiki](https://github.com/obsproject/obs-studio/wiki/install-instructions).

Since [the patch above](https://github.com/obsproject/obs-browser/issues/219#issuecomment-769262132) was merged in obsproject/obs-studio#4155, and we're now using CEF 4280 on Linux for OBS Studio 27, we consider this Issue to be fixed.  As such, I'm closing this.

**Comment by hollunder** [comment]
Will you enable this plugin in your official builds again?
This issue is mentioned as the reason for why it is not.
See for example https://github.com/obsproject/obs-browser

**Comment by Gol-D-Ace** [comment]
@hollunder 
The plugin is already enabled in 26.1.1 Ubuntu PPA builds and will be updated in v27 to a newer version.

**Comment by eliezerlp** [comment]
Would it be helpful if a PR is submitted to update the README.md?

**Comment by Fenrirthviti** [comment]
This issue was resolved already. What update are you looking to make?

**Comment by eliezerlp** [comment]
As mentioned by @hollunder:
> This issue is mentioned as the reason for why it is not.
> See for example https://github.com/obsproject/obs-browser


In README.md it mentions the following:
`**This plugin is included by default** on official packages on Windows and macOS. While Linux is supported, the official ppa does not currently include the browser source due to a conflict with GTK.`

**Comment by Fenrirthviti** [comment]
Ah, yes please feel free to submit an update for that!

**Comment by qroft** [comment]
I am currently changing from Win10 to Ubuntu. 
Can anyone confirm me that the browser source still is not working with the latest stable release?
At least i can not see it in my sources. Greetings everyone!

**Comment by Gol-D-Ace** [comment]
Hi
How did you install OBS on Ubuntu?

Only the PPA, Flatpak and Snap have the browser source available there.

Does your OBS say dfsg in the window title? If so you are using the Debian repo Version which lacks the browser source, VST and FTL

**Comment by qroft** [comment]
> Hi How did you install OBS on Ubuntu?
> 
> Only the PPA, Flatpak and Snap have the browser source available there.
> 
> Only the PPA has and the Flatpak will have the service integrations available.
> 
> Does your OBS say dfsg in the window title? If so you are using the Debian repo Version which lacks the browser source, VST and FTL

Thanks a lot, you are right. I had to use a workaround and installed the linuxBrowser plugin.
Thanks for your time!
